version: '3.1'
services:
  idefendapi:
    build: ./iDefendApi
    image: idefendapi
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal var_display_max_depth=-1 var_display_max_children=-1 var_display_max_data=-1"